from runtime.sim import DistProcess

global DistProcess
global TIMEOUT
TIMEOUT = 5

dist_source("opt.dis")

def config():
    nproposers = 10
    nacceptors = 150

    acceptors = createprocs(Acceptor, nacceptors, [])
    proposers = createprocs(Proposer, nproposers,
                            [acceptors, nproposers+nacceptors, nacceptors/2])

    config_max_event_timeout(1)
    config_sim_total_units(1)
