TIMEOUT = 1
dist_source("byzpaxos.dis")

def main():
    nproposers = 10
    nacceptors = 25
    f = (nacceptors -1)/3

    acceptors = createprocs(Acceptor, nacceptors)
    proposers = createprocs(Proposer, nproposers)

    setupprocs(acceptors, [acceptors | proposers, f])
    setupprocs(proposers, [acceptors, nacceptors/2+f, f])

    config_sim_total_units(proposers, 1)
    config_total_units(nproposers)

    startprocs(acceptors)
    startprocs(proposers)
