TIMEOUT = 3
dist_source("opt.dis")
def main():
    nproposers = 10
    nacceptors = 150
    f = int((nacceptors - 1)/3)

    acceptors = createprocs(Acceptor, nacceptors)
    proposers = createprocs(Proposer, nproposers)

    config_sim_total_units(proposers, 1)
    config_total_units (nproposers)

    setupprocs(acceptors, [acceptors | proposers, nacceptors/2+f, f])
    setupprocs(proposers, [acceptors, nacceptors/2+f, f])

    startprocs(acceptors | proposers)
