import random
TIMEOUT = 3
dist_source("hsleader.dis")

def main():
    n = 10
    ps = createprocs(P, n)
    topology = [p for p in ps]
    random.shuffle(topology)
    for i, p in enumerate(topology):
        if i == 0:
           setupprocs([p], [topology[-1], topology[1]])
        elif i == len(topology)-1:
           setupprocs([p], [topology[-2], topology[0]])
        else:
           setupprocs([p], [topology[i-1], topology[i+1]])

    startprocs(ps)
